# Generated by Django 4.2.11 on 2024-10-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_books', 'Can add new books')]},
        ),
    ]
