# Generated by Django 5.1.2 on 2024-10-29 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='published_date',
            new_name='established_date',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (10-15 digits) with an optional leading '+' sign.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
